### ISSUE TITLE
Questions about this hook

### ISSUE THREAD

**Issue by Berthog** [Dir-A/CMVS-Tools#1]
Hello. Thank you very much for this hook, it looks very interesting and it would very useful for this kind of engines. I have some questions. Under what conditions the hook works? I mean, the cpz files should be extracted in a specific way? (For example, there's tools that extract cpz files with the encode, but others that extract it without the encode) my second question is, would you give more details about how this hook works and how could we modify for different cmvs games? And final question, well, doubt, is that I tested it with Kunado but didn't worked for some reason unknow for me, so maybe I'm doing something wrong. Thank you very much in advance!

**Comment by Dir-A** [comment]
Hi,Bro.I recorded a quick guide video link here:https://www.bilibili.com/video/BV1Bt4y1G7f1
For this engine cpz pack there are two general formats .pb3 .ps3
Some older versions may be .pb2 .pss .ps2
.pb3 .pb2 It is a picture format.
.ps3 .ps2 .pss It is a script format.

I'll introduce . pb3 and . ps3,
.pb2 and .pss .ps2 are a little different, but similar

.pb3 is a picture format.
if you unpack with GarBro,Can't be read directly by CMVS. 
That's because GarBro decode this file.
In other words GarBro unpacked files is not the Raw data.
You can use https://github.com/xmoeproject/CMVS-Engine projet's tools to extract .pb3 files.
Can be read by CMVS.
I don't have much time to adapt the GarBro unpacked files.
Actually I don't need to adapt it either.
Because there is no tools to repack .pb3 file,And CMVS can read image as .bmp or .png.
Just Convert .pb3 to .png or .bmp,Modify the image and rename .png or .bmp to .pb3.

.ps3 is a script format.The Raw data is encrypted.
the first is xor and the Second is Compression.
if you unpacked with GarBro It's been decrypted.
You can use a hex editor and switch the encoding to cp932,rolling pulley to the bottom can see the text.
Normally CMVS can't read .ps3 unpacked by Garbro.
But CmvsFileHook can do that.That's why in dllmain.cpp you can see this *(BYTE*)0x0046CEF1 = 0xEB.
That's to jump the Decryption algorithm (xor and decompress).
Enables CMVS to read both decrypted and encrypted .ps3 files.

Some older games may not work directly,But the core logic is the same.
When the engine reads a file it will determine the path of the file.
If the path ends with char "\\" it will jump to the [read from folder] code.
If not it will jump to the [read from pack] code.
You just need to find this place,then you can control how the files are read.

I wrote a blog about it，If you can read Chinese
https://www.cnblogs.com/Dir-A/p/16552781.html

**Comment by Cosetto** [comment]
But the Purpleps3packer needs encrypted .ps3 to pack back right? Is there anyway to get original ps3, [this one](https://github.com/Yggdrasill-Moe/Niflheim/tree/master/cmvs) only work for the ps3 it decodes. Btw what was the background music you use in the video

Edit: I found this python code for extracting and inserting script of unencrypted script for Aoitori on one of the issues [link](https://github.com/Yggdrasill-Moe/Niflheim/files/8551203/Aoitori.zip) , and for some reason it inserts nothing when I try inserting it back,

**Comment by Berthog** [comment]
Thank you very much for your reply bro! I just have 1 problem here. I tested it with Seishun Fragile as you did in your video, and everything gone well, but in the case of ps3 files, I use, for example, a decompiler to convert it to .txt and from .txt to ps3 again. When I do that, the hook stop to working on that script, it just works when I edit it in a hex editor. What do you think would be the reason? I'll annex the tools that I use for ps3 files. 
[ps3 tools.zip](https://github.com/Dir-A/CmvsFileHook/files/9331664/ps3.tools.zip)

Also here's the hook.dll that we edited. 
[CmvsFileHook.zip](https://github.com/Dir-A/CmvsFileHook/files/9331673/CmvsFileHook.zip)

**Comment by Cosetto** [comment]
So after thinking a little bit, I found a way to do it.
First, use GARbro to extract the script from script.cpz
Next, use Ps3textdumper to edit and Purpleps3packer to pack the script, it should give you new encrypted script
Finally, use the [pb3_decoder](https://github.com/Yggdrasill-Moe/Niflheim/tree/master/cmvs/ps3_decoder) to decrypt the script
So my guess is the decoder didn't work correctly, so it crashed for Berthog?

**Comment by Dir-A** [comment]
BGM in video: 幻想症候群[with]Marcia.  https://music.163.com/#/song?id=1952853537&userid=129733524

I don't know about Purpleps3packer，but Cosetto mentioned python script work well in Seishun Fragile。
Usage:
In the same directory as the python script,create a folder with the name "code"
and rename .ps3 to .ps3.dec place in "code" folder.run cmvs_textdump.py you can get .txt
After modifying the text run cmvs_textimport.py to repack it.

You can provide your .ps3 file, let me see what the problem is.

I don't really like the import method of those tools.It may cause many problems.
.ps3 dump / insert is very simple.You can divide the ps3 file into three areas.
Header Section,OPCODE Section,String Section
The normal size of the Header Section is 0x30,or you can seek in file offset 0x4.
OPCODE Section immediately follows Header Section.
String Section can be calculated from the members of the Header Section.
OPCODE Section there is something like push string. [push string 0x00000A00 ,push string 0x0000AB12]
The address is an offset relative to the String Section.
You can check the source code of those tools for details.

So we don't need to modify the string in the original place.
Just append the string[ends with 0x00] to the end of the file,
Then change the offset from the OPCODE Section. like this [push string sizeof(String Section)+offset ].
Remember to change the size of String Section in the last member of Header Section.

Some tips:
Both of those tools are developed for Chinese.
That means they extract the text using cp932 repack with cp936.
Some Japanese characters may be lost,this may cause problems.
You better modify them dump with cp932 repack with cp932,or modify source code like I said above.

**Comment by Berthog** [comment]
> You can provide your .ps3 file, let me see what the problem is.

Here's my script bro. 
[code.zip](https://github.com/Dir-A/CmvsFileHook/files/9332197/code.zip)

**Comment by Berthog** [comment]
> You can provide your .ps3 file, let me see what the problem is.

 I first extracted script.cpz with garbro and then renamed the .ps3 to .ps3.dec as you said and runned the dumper, but it got a problem in the importer, still the python code creates a new .ps3 but it crashes in the game. 
update: I miss 1 step, change the codification of insert to cp932, I did it as you said and it worked, thank you!
Also thank you very much for details, it's so useful. As I imagine you have learned more about this engine, can I ask if you have read or find something about the font? I know that the font can be changed from config in the game, and also from cmvsconfig, but I wonder if there's also a way to change font size and wordwrap.

**Comment by Dir-A** [comment]
I rarely get involved in localization projects，So I'm not sure about this aspect.
Wordwrap:
Maybe there is a connection with the punctuation characters in the script files[.ps3] or exe or you can try '\n'.
In some cases it is also related to character boundaries or specific characters（Written in Asm）.
![QQ截图20220814071203](https://user-images.githubusercontent.com/79064817/184516284-4fc9d019-f271-47fc-b614-b4575801f400.png)

Font Size:
The font size is probably controlled by the engine's virtual machine, which is not very easy to change.
But the game settings provide three size options. 大 Large 中 Medium 小Small
![QQ截图20220814070404](https://user-images.githubusercontent.com/79064817/184516134-860d4a4c-6f10-45b0-a6a7-07abb44668ae.png)

Font Name:
I don't know if you can use x64dbg.
Changing the font is very simple,
https://docs.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-createfonta
take a look msdn the last member of CreateFontA is the font name
you can hook this func or just find the font name string in exe.
![QQ截图20220814064953](https://user-images.githubusercontent.com/79064817/184515995-deb39f4c-1c91-4f84-92ec-3dd415266710.png)

using x64dbg open exe
switch to memory map and press ctrl + b or right click select Find Pattern
Search default font name: ＭＳ ゴシック
You may get several results,Change them to the font name you want and save into a new exe.
Maybe this doesn't work some times.You can check WINAPI EnumFontFamilies.
This api is like a filter that will filter out fonts that don't match the current game language.
like this:
![QQ截图20220814065045](https://user-images.githubusercontent.com/79064817/184516020-544c2b9b-e1b2-44ce-9dc4-1d4088132e02.png)
![QQ截图20220814065348](https://user-images.githubusercontent.com/79064817/184516043-c0dd4e6b-d9c1-4b9a-be1e-55344a75acb3.png)
![QQ截图20220814065427](https://user-images.githubusercontent.com/79064817/184516048-8a962978-3fa1-48ec-9f4a-bfa81f7aeac1.png)
![QQ截图20220814065508](https://user-images.githubusercontent.com/79064817/184516051-cbe1a61c-76c0-4134-b96a-e49f45a3b278.png)
![QQ截图20220814065526](https://user-images.githubusercontent.com/79064817/184516053-8b984f2c-837c-4ccc-807e-736f1449a243.png)

**Comment by Berthog** [comment]
Thank you very much for your detailed answers! All works perfectly for now. I have still try the process for dump and insert the .ps3 without those tools that we listed above, but for now my questions are solved, so I'm closing this issue. Thank you very much again and if I have another question later I'll reopen (in case you are available and have time to answer of course)

**Comment by Cosetto** [comment]
@Dir-A Bro I saw your video on how to bypass new cxdec but I can't comment, I wanna ask is there any quicker way to do it or an exe that can do it? The game want to crack is the steam version of [this game](https://vndb.org/v24717)

**Comment by Dir-A** [comment]
check this https://github.com/sst311212/FuckBootStrap
Compile and get version.dll.
Just put version.dll in the game directory and start game.

**Comment by Cosetto** [comment]
wow, thanks a lot bro, but can we somehow extract all files at once?

**Comment by Dir-A** [comment]
It is a complex issue.My friend has tried and succeeded in unpacking all the files.
But there are several problems, no file name, no path.
Essentially, the new cxdec encrypted files are just xor, but the xor key is different for each file.
The algorithm for filenames and paths is very complex.

Obviously, I don't see anyone who has fully analyzed new cxdec now either
I just want to tell you that it is not possible to unpack the cxdec files in once without completely reverse analyzing them.

**Comment by xenei** [comment]
Hello brother. On the topic of hooks, I was wondering if it could be possible to make a hook/ or hack for new version Seen.txt of RealLive engine? Since nobody has attempted to decrypted Seen.txt from new version, I wonder if the new encryption of RealLive is like Siglus? Such game as this : https://vndb.org/v28285 ; uses new version of RealLive engine and any old tools do not work with them

**Comment by Cosetto** [comment]
@Dir-A bro if you're wondering about .cmv then [this repos](https://github.com/pkuislm?tab=repositories)  could help, it has cmv decode/encode tools

**Comment by Lebedev30** [comment]
In the new version of hook where do I put the entry points?
There is no mention of it at all in the dllmain files.
Is the hook working now?

**Comment by ManhKun97** [comment]
Anyone has tool to repack ps2.txt file to ps2 file? I already translated mirai nostalgia but can repack it to ps2 file
