### ISSUE TITLE
ps3_texteditor bug

### ISSUE THREAD

**Issue by Cosetto** [Dir-A/CMVS-Tools#6]
Hey bro, I notice there's a weird bug with ps3_texteditor. There were some weird characters appeared when Japanese characters stood next to half-width characters
![image](https://github.com/Dir-A/CMVS_Tools/assets/81801486/f57fa61f-6c98-46aa-9f30-43ec18c5acdf)

**Comment by Dir-A** [comment]
upload .ps3 .json ，I'll take a look at it when I have time.

**Comment by Cosetto** [comment]
[Sample.zip](https://github.com/Dir-A/CMVS_Tools/files/15173948/Sample.zip) ([Aoi Tori English verion](https://f95zone.to/threads/aoi-tori-v1-01-purple-software.206084/))
I also tried with [this tool](https://github.com/Yggdrasill-Moe/Niflheim/blob/master/cmvs/cmvs_textimport.py), it doesn't leave weird characters, yet it messed up the floating textbox.
![image](https://github.com/Dir-A/CMVS_Tools/assets/81801486/8dbdec13-2b8e-4540-8118-7f9dec5da70b)

**Comment by Cosetto** [comment]
Bro, can you also make guide for https://github.com/Dir-A/VNSubtitle when you are free?

**Comment by Dir-A** [comment]
the import tool has no problem and you can see that the string is correctly encoded in memory
![QQ截图20240515231804](https://github.com/Dir-A/CMVS_Tools/assets/79064817/87ea2f4b-bf08-419c-a8b2-659eed60e17f)

so why there is a problem in the text box?
![QQ截图20240515231804](https://github.com/Dir-A/CMVS_Tools/assets/79064817/b191ed45-c6c2-4d40-b61c-ddc8af1ab26b)

I found this function, in short this is a virtual machine function to deal with a certain instruction, its function is to cut a character in the string, of course, this character has to go through the sjis check first, if it is a sjis character then cut two bytes, otherwise cut one byte save into a buffer.
![QQ截图20240515233851](https://github.com/Dir-A/CMVS_Tools/assets/79064817/a3b25afe-4145-4140-b009-89bdbde74b20)


the difference between the English and Japanese versions is that the English version uses the game's script to reprocess the strings, but it does so for English, i.e. single-byte, which leads to problems with the processed strings.
![QQ截图20240515235844](https://github.com/Dir-A/CMVS_Tools/assets/79064817/ec4e12db-4415-4d50-9509-d2498c5f5cfa)

the problem lies in the function `sys_lstrncut(str_index_in_strtable,cat_count,str_read_char_cout)` of vm.
https://github.com/Dir-A/CMVS_Tools/blob/main/etc/note.md#systemcommand
since the english version of the script is only designed to handle english characters, the parameter `str_read_char_cout` passed to `sys_lstrncut` only increases by 1 each time.
that is fine for english (single-byte), but for sjis (double-byte) it points to the wrong character.

there are two way that might work 
1, if we can find out why or where it increases by 1 each time
2, modify sys_lstrncut

**Comment by Cosetto** [comment]
Well, this is weird, I tried using Seishun Fragile's exe on Aoi Tori since both use the same version and hook addresses. Seishun Fragile doesn't have that problem, but Aoi Tori remains the same.

**Comment by MishaIac** [comment]
It's about the bytes I highlighted in the screenshot. Bytes at address `0x61B00` and `0x61B0D` are most likely responsible for how to encode text in the textbox and in the backlog. The rest seem to be responsible for the window itself, where the text is displayed. The reason the [Niflheim tool](https://github.com/Yggdrasill-Moe/Niflheim/blob/master/cmvs/cmvs_textimport.py) displays the text correctly, and breaks the textbox, is because it zeroes those 5 bytes, while PS3_TextEditor does not do that. If you zeroes only the two bytes that are responsible for the encoding, the text and textbox will display normally, but wordwrap will stop working. I think if it is `0x20`, the engine reads only one byte, and if it is `0x00`, it reads normally, as it should be.
![image](https://github.com/ZQF-ReVN/CMVS_Tools/assets/47920105/ac67674d-00ab-48ac-9a96-c5ef25d8a6c2)

**Comment by Cosetto** [comment]
So, is there any solution for this?

**Comment by MishaIac** [comment]
> So, is there any solution for this?

I think it's best to leave it so that the engine reads one byte to let wordwrap work. I understand you want to use characters not available in the ascii range? If so, replace the half-width kana, because in SJIS it uses one byte, so wordwrap will work for it too
